// <auto-generated />
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211116122844_SeedProduct")]
    partial class SeedProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Return the product if not happy",
                            ImageUrl = "https://cdotnetmastery.blob.core.windows.net/mango/11.jpg",
                            Name = "Gloucester",
                            Price = 40.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Packs",
                            Description = "Please dont Return the product if not happy",
                            ImageUrl = "https://cdotnetmastery.blob.core.windows.net/mango/12.jpg",
                            Name = "Leroy",
                            Price = 25.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "None",
                            Description = "Please dont Return the product if not happy",
                            ImageUrl = "https://cdotnetmastery.blob.core.windows.net/mango/13.jpg",
                            Name = "Mafokoane",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Nice",
                            Description = "Please dont Return the product if not happy",
                            ImageUrl = "https://cdotnetmastery.blob.core.windows.net/mango/14.jpg",
                            Name = "Esrom",
                            Price = 16.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
